# Markdownlint Configuration for RylanLabs
# Guardian: Carter | Ministry: Standards
# Maturity: v1.0.1

# Exclude LICENSE (not markdown, but text file)
MD041: false

# Allow emphasis as headings (agent specs use for examples)
MD036: false

# Allow multiple H1 headings (agent specs show examples)
MD025: false

# Allow ordered list with invalid prefixes (examples)
MD029: false

# Allow missing code fence language (agent specs show examples of violations)
MD040: false

# Line length - doubled from default 80 to 160
MD013:
  line_length: 160
  heading_line_length: 160
  code_block_line_length: 160
  tables: false
  code_blocks: false

# Allow inline HTML for special cases
MD033: false

# Allow duplicate headings (common in audit logs)
MD024: false

# Default settings for other rules
default: true
